#include <jyotish/oracle.hpp>
#include <jyotish/config.hpp>
#include <string>
#include <vector>
#include <random>

namespace jyotish::oracle {

const std::vector<std::string> QUOTES_RU = {
    "С большой силой приходит большая ответственность.",
    "Вернусь, детка.",
    "Ты это мне сказал?.. Со мной говоришь?",
    "Это, скорее всего, любовь.",
    "Нет повести печальнее на свете, чем повесть о Ромео и Джульетте.",
    "Если не уверен, не рискуй.",
    "Ум — всё. Чем ты думаешь, тем ты и становишься.",
    "Ты сам, как никто другой, заслуживаешь своей любви.",
    "Не останавливайся на прошлом, не мечтай о будущем, сосредоточь ум на настоящем.",
    "Лучше путешествовать, чем прибыть.",
    "Ненависть не прекращается ненавистью — ненависть прекращается только любовью.",
    "Как ветер не может поколебать гору, так похвала и хула не колеблют мудреца.",
    "Счастье не уменьшается от того, что им делимся.",
    "Ничто не вечно, кроме перемен.",
    "Кто победил себя, тот сильнее того, кто победил тысячу тысяч.",
    "Слова имеют силу и в начале, и в конце; выбирай их мудро.",
    "Не зацикливайся на том, что было, и не грези о том, что будет; живи настоящим.",
    "Лучше владеть собой, чем владеть целым миром.",
    "Тише едешь — дальше будешь.",
    "Лучше синица в руках, чем журавль в небе.",
    "Медленно, но верно.",
    "В единстве сила: палку легко переломить по одной, а пучок — нет.",
    "Не гонись за двумя зайцами.",
    "Кто слишком полагается на удачу, тот терпит крах.",
    "Не доверяй сладким речам, пока не увидишь дел.",
    "То, что нас не убивает, делает нас сильнее.",
    "Будь собой — все остальные роли уже заняты.",
    "Единственный способ делать великие дела — любить то, что делаешь.",
    "Жизнь — это то, что происходит, пока ты строишь планы.",
    "Мы — то, что мы делаем постоянно; совершенство — не поступок, а привычка.",
    "Человек — кузнец своего счастья.",
    "Трудности закаляют характер, как огонь закаляет сталь.",
    "Упади семь раз — поднимись восемь.",
    "Путь в тысячу миль начинается с одного шага.",
    "Каждая неудача — это урок, а не приговор.",
    "Терпение и труд всё перетрут.",
    "Не ошибается лишь тот, кто ничего не делает.",
    "У страха глаза велики.",
    "Всё тайное становится явным.",
    "Семь раз отмерь — один раз отрежь.",
    "Гора не кажется непреодолимой, когда идёшь маленькими шагами.",
    "Дорогу осилит идущий.",
    "Лучшее время посадить дерево было двадцать лет назад; следующее — сейчас.",
    "Свернуть горы можно только постепенно: камень за камнем.",
    "Кто ищет — тот найдёт.",
    "Настойчивость побеждает там, где сила сдаётся.",
    "Мудрый учится на чужих ошибках, глупец — на своих.",
    "Не бойся медленно идти — бойся стоять на месте.",
    "Великие дела начинаются с малых.",
    "Что посеешь, то и пожнёшь.",
    "Всему своё время.",
    "Друг в беде — настоящий друг.",
    "Скромность красит человека.",
    "Лучше честная бедность, чем богатство обманом.",
    "Гнев — начало безумия.",
    "Тише вода — глубже омут.",
    "Умение прощать — признак силы, а не слабости.",
    "Красота спасёт мир, а доброта — каждый день.",
    "Самый тёмный час — перед рассветом.",
    "Счастье любит тишину.",
    "Не всё то золото, что блестит.",
    "Цена урока измеряется не тем, что ты заплатил, а тем, что ты понял.",
    "Говори правду, и тебе не нужно будет ничего запоминать.",
    "Сила не в том, чтобы ударить, а в том, чтобы не ударить, когда можешь.",
    "Ты не можешь управлять ветром, но можешь поставить паруса.",
    "Надейся на лучшее, готовься к худшему.",
    "Не суди о книге по обложке.",
    "Каждый человек — автор своей судьбы.",
    "Лучше поздно, чем никогда.",
    "Рана от слов заживает дольше, чем рана от ножа.",
    "Доверие теряют быстро, а зарабатывают годами.",
    "Чем выше летаешь, тем больнее падать — но тем больше видно.",
    "Не рой яму другому — сам в неё попадёшь.",
    "Красота приходит изнутри, как свет из глубины души.",
    "Побеждает не тот, кто сильнее, а тот, кто верит до конца.",
    "Сердце знает то, что не знает разум.",
    "Любовь — единственное, что растёт, когда его отдаёшь.",
    "Время лечит, но след остаётся.",
    "Изумруд нельзя отполировать без трения, человека — без испытаний.",
    "Мудрец не делает того, о чём пожалеет.",
    "Солнце не ждёт, когда ему скажут спасибо, — оно просто светит.",
    "Истина всегда посередине, но путь к ней — через крайности.",
    "Долгих дорог не бывает для тех, кто идёт весело.",
    "Не жди идеального момента — используй этот.",
    "Ты волнуешься о том, что мир не одобряет; мудр тот, кто не зависит от чужого мнения.",
    "Богатство — не в деньгах, а в привязанностях, которые нельзя купить.",
    "Снизить требования к внешнему — значит поднять планку к свободе.",
    "Талант — это 1% вдохновения и 99% труда.",
    "Действие важнее слов: намерение определяет поступок, поступок — судьбу.",
    "У каждого кризиса есть скрытый дар, если готов его принять.",
    "Рану времени наносят не события, а отношение к ним.",
    "Если хочешь узнать человека, дай ему власть.",
    "Свобода — это когда сам выбираешь, чему служить.",
    "Никогда не сдавайся: судьба любит упрямых.",
    "Целься в луну: даже если промахнёшься, останешься среди звёзд.",
    "Мечты сбываются у тех, кто не боится идти за ними.",
    "Пока есть жизнь, есть надежда.",
    "Сердце и разум — друзья, если их познакомить.",
    "Лучший способ предсказать будущее — создать его.",
    "Иногда нужно отступить на шаг, чтобы прыгнуть дальше.",
    "Не сравнивай себя с другими — сравнивай с тем, кем был вчера.",
    "Ошибки — это входные билеты в новую жизнь.",
    "Завтрак съешь сам, обедом поделись, ужин отдай врагу.",
    "Вода камень точит.",
    "Клин клином вышибают.",
    "Без труда не вытащишь и рыбку из пруда.",
    "Слово — серебро, молчание — золото.",
    "Глаза — зеркало души.",
    "Честность — лучшая политика.",
    "Маленькие шаги приводят к большим высотам."
};

const std::vector<std::string> QUOTES_EN = {
    "With great power comes great responsibility.",
    "I'll be back.",
    "Are you talking to me?",
    "Greater love hath no man than this.",
    "It's probably love.",
    "The mind is everything. What you think you become.",
    "You yourself, as much as anybody, deserve your love.",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present.",
    "Hatred is not ceased by hatred, but by love alone.",
    "The one who conquers himself is greater than the one who conquers a thousand thousand.",
    "Nothing is permanent but change.",
    "Slow but steady wins the race.",
    "A little bird in hand is better than two in the bush.",
    "Sticks bound in a bundle cannot be broken apart.",
    "What doesn't kill us makes us stronger.",
    "Everything else will be taken, so be yourself.",
    "The only way to do great work is to love what you do.",
    "Life is what happens to you while you're busy making other plans.",
    "We are what we repeatedly do. Excellence is a habit.",
    "Fall seven times, stand up eight.",
    "A journey of a thousand miles begins with a single step.",
    "Whether you think you can or can't, you're right.",
    "The best time to plant a tree was twenty years ago. The second best time is now.",
    "Difficulty strengthens the mind, as labor does the body.",
    "Patience is bitter, but its fruit is sweet.",
    "The darkest hour is just before the dawn.",
    "All that glitters is not gold.",
    "Fortune favors the brave.",
    "Do not judge the book by its cover.",
    "Better late than never.",
    "Where there is a will, there is a way.",
    "It always seems impossible until it is done.",
    "The only journey is the one within.",
    "What you seek is seeking you.",
    "Carve a statue of yourself in every single day.",
    "Do not look back; look forward.",
    "Act well, cook well, live well.",
    "The obstacle is the path.",
    "No act of kindness, no matter how small, is ever wasted.",
    "In the middle of difficulty lies opportunity.",
    "The longest journey begins with a single footstep.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "It's not the years in your life that count; it's the life in your years.",
    "Insanity is doing the same thing over and over and expecting different results.",
    "Happiness depends on ourselves.",
    "He who has a why to live can bear almost any how.",
    "Knowledge speaks, but wisdom listens.",
    "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
    "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
    "The best revenge is massive success.",
    "A friend in need is a friend indeed.",
    "It is not our abilities that show what we truly are; it is our choices.",
    "Tomorrow is always fresh, with no mistakes in it.",
    "We make a living by what we get, but we make a life by what we give.",
    "Be the change you wish to see in the world.",
    "No one can make you feel inferior without your consent.",
    "Whether it's now or later, all things come to those who wait.",
    "Courage is not the absence of fear, but the triumph over it.",
    "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    "Do not watch the clock; do what it does. Keep going.",
    "Success is the sum of small efforts, repeated day after day.",
    "The way to get started is to quit talking and begin doing.",
    "Do not wait for the perfect moment; take the moment and make it perfect.",
    "Better an honest poverty than a deceitful richness.",
    "Harmony makes small things grow; lack of it makes great things decay.",
    "Be kind whenever possible. It is always possible.",
    "Every strike brings me closer to the next home run.",
    "Difficult roads often lead to beautiful destinations.",
    "The wound from words lasts longer than the wound from a blade.",
    "Mix a little foolishness with your serious plans; a bit of nonsense is sweet.",
    "A man's character is his fate.",
    "Happiness is not something ready-made; it comes from your own actions.",
    "Keep your face always toward the sunshine, and shadows will fall behind you.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Everything has beauty, but not everyone sees it.",
    "It is during our darkest moments that we must focus to see the light.",
    "If you want to lift yourself up, lift up someone else.",
    "Our greatest weakness lies in giving up.",
    "The expert in anything was once a beginner.",
    "Change your thoughts and you change your world.",
    "To love and be loved is to feel the sun from both sides.",
    "The secret of getting ahead is getting started.",
    "Hard choices, easy life. Easy choices, hard life.",
    "A smooth sea never made a skilled sailor.",
    "Light travels faster than sound, so people appear bright until you hear them speak.",
    "The only way out is through.",
    "Gratitude turns what we have into enough.",
    "A river cuts through rock, not because of its power, but because of its persistence.",
    "Don't count the days; make the days count.",
    "What we resist persists.",
    "When you have exhausted all possibilities, remember this: you haven't.",
    "Every exit is an entry somewhere else.",
    "Kindness is a language the deaf can hear and the blind can see.",
    "The man who moves a mountain begins by carrying away small stones.",
    "It is not the mountain we conquer, but ourselves.",
    "When you want something, all the universe conspires in helping you to achieve it.",
    "The best time to begin is now; perfect conditions never come.",
    "Adversity reveals genius; prosperity conceals it.",
    "A gem is not polished without friction, nor a person perfected without trials.",
    "The wise man does not lay up his own treasures; the more he gives to others, the more he has.",
    "He who angers you conquers you.",
    "Clouds come floating into my life, no longer to carry rain, but to add color to my sunset sky.",
    "Bodily endurance is a virtue, but spiritual endurance is a mountain."
};

std::vector<std::string> sample_quotes(const std::string& lang, int n) {
    const auto& pool = lang == "ru" ? QUOTES_RU : QUOTES_EN;
    std::vector<std::string> result;
    std::mt19937 rng(std::random_device{}());
    std::vector<int> indices(pool.size());
    std::iota(indices.begin(), indices.end(), 0);
    std::shuffle(indices.begin(), indices.end(), rng);
    for (int i = 0; i < std::min(n, static_cast<int>(pool.size())); ++i) {
        result.push_back(pool[indices[i]]);
    }
    return result;
}

} // namespace jyotish::oracle