#!/usr/bin/env bash
# Server-side setup for the Jyotish oracle on a fresh Ubuntu 24.04 KVM VPS.
# Run as root, AFTER deploy/upload.sh has placed files in /opt/oracle.
# Idempotent: safe to re-run.
#
#   DOMAIN=zvezdakot.ru ALT_DOMAIN=zvezdakot.rf bash server-setup.sh
#
set -euo pipefail

DOMAIN="${DOMAIN:?set DOMAIN, e.g. DOMAIN=zvezdakot.ru}"
ALT_DOMAIN="${ALT_DOMAIN:-}"
CERT_DOMAINS=(-d "$DOMAIN")
[[ -n "$ALT_DOMAIN" ]] && CERT_DOMAINS+=(-d "$ALT_DOMAIN")

ORACLE_DIR=/opt/oracle
BIN="$ORACLE_DIR/build/jyotish_server"
DIST="$ORACLE_DIR/dist"
ENV_FILE="${ENV_FILE:-/etc/oracle.env}"
UNIT=/etc/systemd/system/oracle.service
NGINX_SITE=/etc/nginx/sites-available/oracle
SSL_DIR=/etc/letsencrypt/live/$DOMAIN
TAG=oracle-setup

log() { printf '[%s] %s\n' "$TAG" "$*"; }
die() { printf '[%s] ERROR: %s\n' "$TAG" "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "run as root"
[[ -f "$BIN" ]] || die "missing $BIN — run deploy/upload.sh first"
[[ -d "$DIST" ]] || die "missing $DIST — run deploy/upload.sh first"
file "$BIN" | grep -q ELF || die "$BIN is not an ELF binary"

if [[ -r /etc/os-release ]]; then
  # shellcheck disable=SC1091
  . /etc/os-release
  log "OS: $PRETTY_NAME"
  [[ "$ID" == ubuntu ]] || log "WARNING: expected Ubuntu, found $ID"
fi

# Swiss Ephemeris is linked statically (libswe.a from ~/.local/lib), so no
# ephemeris package is required. swe_set_ephe_path(nullptr) with no .se1 files
# present means Swiss Ephemeris falls back to the Moshier analytical theory,
# which is what the current production server already does. Installing .se1 here
# would shift planet positions slightly versus the stored charts, so don't.

# --- 1. packages ------------------------------------------------------------
export DEBIAN_FRONTEND=noninteractive
log "installing packages"
apt-get update -qq
apt-get install -y -qq --no-install-recommends \
  nginx certbot python3-certbot-nginx curl ca-certificates rsync sqlite3 ufw tzdata

# --- 2. layout --------------------------------------------------------------
log "preparing $ORACLE_DIR"
mkdir -p "$ORACLE_DIR/build" "$DIST"
chmod 0755 "$ORACLE_DIR" "$ORACLE_DIR/build"
# oracle.service declares no User=, so it runs as root and needs write access to
# the SQLite store and the feedback / news cache directories. This matches the
# current deployment; dropping to a dedicated user is a separate hardening step.
chmod -R u+rwX,go+rX "$ORACLE_DIR"

# --- 3. runtime environment -------------------------------------------------
# Values are carried over from the old server so that payments, the admin login
# and the LLM behaviour survive the migration. Pass LEGACY_ENV=<path to the old
# /etc/oracle.env> on the first run; an existing $ENV_FILE always wins.
#
#   LEGACY_ENV=/root/old-oracle.env DOMAIN=... bash server-setup.sh
#
# The old file is parsed, not sourced: it holds secrets and may predate this
# script, so nothing in it should be executed.
declare -A CARRY=()
load_env() {
  local file="$1" line key value
  [[ -r "$file" ]] || { log "no readable env at $file, skipping"; return 0; }
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%$'\r'}"
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" =~ ^[[:space:]]*(export[[:space:]]+)?([A-Z_][A-Z0-9_]*)[[:space:]]*=[[:space:]]*(.*)$ ]] || continue
    key="${BASH_REMATCH[2]}"
    value="${BASH_REMATCH[3]}"
    value="${value%"${value##*[![:space:]]}"}"   # rtrim
    value="${value%\"}"; value="${value#\"}"
    value="${value%\'}"; value="${value#\'}"
    CARRY["$key"]="$value"
  done < "$file"
  log "loaded ${#CARRY[@]} keys from $file"
}

load_env "${LEGACY_ENV:-}"
if [[ -f "$ENV_FILE" ]]; then
  log "$ENV_FILE exists, its values take priority"
  load_env "$ENV_FILE"
fi

[[ -n "${CARRY[JYOTISH_ADMIN_TOKEN]:-}" ]] || CARRY[JYOTISH_ADMIN_TOKEN]="$(openssl rand -hex 32)"
CARRY[JYOTISH_ADMIN_USER]="${CARRY[JYOTISH_ADMIN_USER]:-albadmin}"
CARRY[JYOTISH_STORE_PATH]="$ORACLE_DIR/oracle_store.db"
CARRY[JYOTISH_CHAT_MODEL]="${CARRY[JYOTISH_CHAT_MODEL]:-qwen2.5:7b-instruct}"
CARRY[JYOTISH_FREE_QUESTIONS]="${CARRY[JYOTISH_FREE_QUESTIONS]:-5}"
CARRY[JYOTISH_COINS_PER_PACK]="${CARRY[JYOTISH_COINS_PER_PACK]:-10}"
CARRY[JYOTISH_COIN_PACK_PRICE_RUB]="${CARRY[JYOTISH_COIN_PACK_PRICE_RUB]:-100}"
CARRY[JYOTISH_SESSION_TTL_DAYS]="${CARRY[JYOTISH_SESSION_TTL_DAYS]:-30}"
CARRY[JYOTISH_MAX_REPLY_CHARS]="${CARRY[JYOTISH_MAX_REPLY_CHARS]:-1200}"

# JYOTISH_HOST, JYOTISH_PORT and OLLAMA_BASE_URL stay in the unit, so a lost
# env file can never leave the server bound to 0.0.0.0 (main_server.cpp:16).
unset CARRY[JYOTISH_HOST] CARRY[JYOTISH_PORT] CARRY[OLLAMA_BASE_URL]

umask 077
{
  echo "# Generated by server-setup.sh — contains secrets, mode 0600."
  echo "# JYOTISH_HOST, JYOTISH_PORT and OLLAMA_BASE_URL live in oracle.service."
  for key in "${!CARRY[@]}"; do printf '%s=%s\n' "$key" "${CARRY[$key]}"; done
} > "$ENV_FILE"
chmod 0600 "$ENV_FILE"
log "wrote $ENV_FILE with ${#CARRY[@]} keys"

# These two silently break revenue and admin access if lost.
[[ -n "${CARRY[JYOTISH_TOPUP_PHONE]:-}" ]] \
  || log "WARNING: JYOTISH_TOPUP_PHONE is not set — the СБП top-up button will not show a number"
[[ -n "${CARRY[JYOTISH_TOPUP_URL]:-}" ]] \
  || log "note: JYOTISH_TOPUP_URL is unset, top-up falls back to the phone above"
ADMIN_TOKEN="${CARRY[JYOTISH_ADMIN_TOKEN]}"

# --- 4. systemd -------------------------------------------------------------
log "installing systemd unit"
install -m 0644 "$(dirname "$0")/oracle.service" "$UNIT"
systemctl daemon-reload
systemctl enable --now oracle
sleep 2
if ! systemctl is-active --quiet oracle; then
  journalctl -u oracle -n 40 --no-pager || true
  die "oracle.service failed to start"
fi
log "oracle.service active"

# --- 5. nginx ---------------------------------------------------------------
# The C++ server serves only /api/*, /health and /healthz on 127.0.0.1:8000 and
# no static files, so nginx terminates TLS and serves $DIST.
SERVER_NAMES="$DOMAIN"
[[ -n "$ALT_DOMAIN" ]] && SERVER_NAMES="$DOMAIN $ALT_DOMAIN"

write_nginx() { # $1 = "http" or "https"
  local mode="$1"
  {
    if [[ $mode == http ]]; then
      cat <<NGINX
server {
    listen 80;
    listen [::]:80;
    server_name $SERVER_NAMES;

    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / { return 301 https://\$host\$request_uri; }
}
NGINX
    else
      cat <<NGINX
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name $SERVER_NAMES;

    ssl_certificate     $SSL_DIR/fullchain.pem;
    ssl_certificate_key $SSL_DIR/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_stapling on;
    ssl_stapling_verify on;

    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    root $DIST;
    index index.html;
    client_max_body_size 12m;

    gzip on;
    gzip_vary on;
    gzip_types text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;

    # SSE: oracle answers stream from the LLM, so never buffer or time them out.
    location /api/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_buffering off;
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
    }

    location = /healthz { proxy_pass http://127.0.0.1:8000/healthz; access_log off; }
    location = /health  { proxy_pass http://127.0.0.1:8000/health;  access_log off; }

    location /assets/ { expires 30d; add_header Cache-Control "public, immutable"; }
    location /fonts/  { expires 30d; add_header Cache-Control "public, immutable"; }

    location / { try_files \$uri \$uri/ /index.html; }
}
NGINX
    fi
  } > "$NGINX_SITE"
  chmod 0644 "$NGINX_SITE"
  ln -sfn "$NGINX_SITE" /etc/nginx/sites-enabled/oracle
  rm -f /etc/nginx/sites-enabled/default
}

log "installing nginx site (HTTP first, for the ACME challenge)"
write_nginx http
nginx -t
systemctl reload nginx

# --- 6. TLS -----------------------------------------------------------------
log "requesting Let's Encrypt certificate for: ${CERT_DOMAINS[*]}"
if [[ -f "$SSL_DIR/fullchain.pem" ]] || certonly_out=$(certbot certonly --nginx -n \
      --agree-tos --register-unsafely-without-email \
      --cert-name "$DOMAIN" "${CERT_DOMAINS[@]}" 2>&1); then
  log "certificate ready"
else
  printf '%s\n' "$certonly_out" >&2
  die "certbot failed — check that $DOMAIN resolves to this server, then re-run"
fi

write_nginx https
nginx -t
systemctl reload nginx
systemctl enable --now certbot.timer
log "TLS enabled"

# --- 7. firewall ------------------------------------------------------------
# 443/udp is Hysteria. 11434 (Ollama) and 8000 stay closed on purpose: Ollama is
# reachable only through the reverse SSH tunnel bound to 127.0.0.1.
log "configuring ufw"
ufw --force reset >/dev/null
ufw default deny incoming >/dev/null
ufw default allow outgoing >/dev/null
ufw allow 22/tcp  >/dev/null
ufw allow 80/tcp  >/dev/null
ufw allow 443/tcp >/dev/null
ufw allow 443/udp >/dev/null
ufw --force enable >/dev/null
ufw status verbose || true

# --- 8. SQLite backups ------------------------------------------------------
log "installing backup timer"
mkdir -p /root/oracle-backups

cat > /usr/local/sbin/oracle-backup.sh <<'BACKUP_EOF'
#!/usr/bin/env bash
# SQLite snapshot via .backup so WAL contents are captured consistently.
set -euo pipefail
STORE="${JYOTISH_STORE_PATH:-/opt/oracle/oracle_store.db}"
DEST=/root/oracle-backups
STAMP=$(date +%F-%H%M)
mkdir -p "$DEST"
sqlite3 "$STORE" ".backup '$DEST/oracle_store-$STAMP.db'"
gzip -f "$DEST/oracle_store-$STAMP.db"
find "$DEST" -name 'oracle_store-*.db.gz' -mtime +14 -delete
BACKUP_EOF
chmod 0750 /usr/local/sbin/oracle-backup.sh

cat > /etc/systemd/system/oracle-backup.service <<'UNIT_EOF'
[Unit]
Description=Snapshot the Jyotish oracle SQLite store

[Service]
Type=oneshot
EnvironmentFile=/etc/oracle.env
ExecStart=/usr/local/sbin/oracle-backup.sh
UNIT_EOF

cat > /etc/systemd/system/oracle-backup.timer <<'TIMER_EOF'
[Unit]
Description=Daily snapshot of the Jyotish oracle SQLite store

[Timer]
OnCalendar=*-*-* 03:30:00
Persistent=true

[Install]
WantedBy=timers.target
TIMER_EOF

systemctl daemon-reload
systemctl enable --now oracle-backup.timer
/usr/local/sbin/oracle-backup.sh
log "backup timer installed, first snapshot taken"

# --- 9. verify --------------------------------------------------------------
log "smoke test"
curl -fsS http://127.0.0.1:8000/healthz; echo
curl -fsS -o /dev/null -w "https /          -> %{http_code}\n" "https://$DOMAIN/"
curl -fsS -o /dev/null -w "https /api/tags  -> %{http_code}\n" "https://$DOMAIN/api/tags"
ss -lntp | grep -E ':(80|443|8000|11434)\b' || true

cat <<SUMMARY

=== done ===
service : systemctl status oracle
health  : curl -s https://$DOMAIN/healthz
admin   : https://$DOMAIN/admin.html
backups : ls -lh /root/oracle-backups

Admin token (also in $ENV_FILE):
  $ADMIN_TOKEN

NEXT, on your workstation — repoint the reverse tunnel to this server:
  systemctl --user edit oracle-tunnel.service     # Server=<new-ip>
  systemctl --user restart oracle-tunnel.service
SUMMARY
